### ISSUE TITLE
AttributeError: module 'tensorflow_core.keras.utils' has no attribute 'register_keras_serializable'

### ISSUE THREAD

**Issue by linaemunsamy** [TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0#7]
hi,

I am fairly new to tensorflow and object detection, however I am trying to get TF2.0+ working.

I am trying to run: python object_detection/builders/model_builder_tf2_test.py

WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "/Users/linaemunsamy/.conda/envs/test/lib/python3.7/site-packages/object_detection/builders/model_builder.py", line 64, in <module>
    from object_detection.models import ssd_efficientnet_bifpn_feature_extractor as ssd_efficientnet_bifpn
  File "/Users/linaemunsamy/.conda/envs/test/lib/python3.7/site-packages/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py", line 33, in <module>
    from official.vision.image_classification.efficientnet import efficientnet_model
  File "/Users/linaemunsamy/.conda/envs/test/lib/python3.7/site-packages/official/vision/image_classification/efficientnet/efficientnet_model.py", line 35, in <module>
    from official.modeling import tf_utils
  File "/Users/linaemunsamy/.conda/envs/test/lib/python3.7/site-packages/official/modeling/tf_utils.py", line 25, in <module>
    from official.modeling import activations
  File "/Users/linaemunsamy/.conda/envs/test/lib/python3.7/site-packages/official/modeling/activations/__init__.py", line 16, in <module>
    from official.modeling.activations.gelu import gelu
  File "/Users/linaemunsamy/.conda/envs/test/lib/python3.7/site-packages/official/modeling/activations/gelu.py", line 26, in <module>
    @tf.keras.utils.register_keras_serializable(package='Text')
AttributeError: module 'tensorflow_core.keras.utils' has no attribute 'register_keras_serializable'

MacOS 10.15.5
Python: 3.7
Tensorflow 2.2
Tensorboard 2.2.1

Any help will be greatly appreciated!

**Comment by TannerGilbert** [comment]
I didn't experience the issue myself and I didn't find any good resolution for the issue. Maybe just try reinstalling Tensorflow 2.2 as it should have the [register_keras_serializable method](https://www.tensorflow.org/api_docs/python/tf/keras/utils/register_keras_serializable). I'll keep looking for a solution and will let you know if I find anything.
